### PR TITLE
Fixed a Hat in Time 60 FPS patch for 1.0.3

### PR DESCRIPTION
**Pull request by skirlez**
I updated the SwitchEngine.ini of a Hat in Time so it would work with the 1.0.3 version of the game.

I tested it and it works.

### CODE REVIEW

**Comment by staringstar** [comment]
The issue with your patch is that in 1.0.3 there were changes to priority so if you already have a savefile, switchengine.ini won't change FPS. It would be really nice if you can find a way to make one 60 FPS mod for people who have and doesn't have already created save. Thanks for your contribution btw.

**Comment by skirlez** [comment]
Weird, Since 60 FPS Works with my old save. I've backed up and deleted my save, Still 60 FPS. Restored the save, and I still have 60 FPS. (Also, We are talking about game saves, not the in-game file saves right?)

**Comment by staringstar** [comment]
Try deleting your save and create a new save without the 60FPS mod in the titles folder, close the game and then add the 60fps mod to the titles folder and see if it is 60fps or not.

**Comment by masagrator** [comment]
> Try deleting your save and create a new save without the 60FPS mod in the titles folder, close the game and then add the 60fps mod to the titles folder and see if it is 60fps or not.

As above.

**Comment by skirlez** [comment]
> Try deleting your save and create a new save without the 60FPS mod in the titles folder, close the game and then add the 60fps mod to the titles folder and see if it is 60fps or not.

Yep, its 30 FPS now. I'll try to find something that does work with a save like this.

**Comment by masagrator** [comment]
I found a way. It was only needed to change
```
[IniVersion]
manual=1
```
to
```
[IniVersion]
manual=0
```

**Pull request closed without merging**
